source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.linphone.org/BC/public/podspec.git'
source 'git@github.com:daltoniam/Starscream.git'

use_frameworks!

platform :ios, '12.0'

target 'DKCloudFramework_Example' do
  pod 'DKCloudFramework', :path => '../'
  pod 'Starscream'
  pod 'linphone-sdk-novideo'
  target 'DKCloudFramework_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
